### PR TITLE
Fetch listing axel

### PR DESCRIPTION
**Pull request by axelnguyen0701**
# Updates
Fetch and create listing is now working
## How to test

1.  Sign up an account on [Infura](https://www.infura.io/)
2.  Set up an IPFS project (tick the dedicated gateway option and give yourself a name, for example: _book-exchange1.infura-ipfs.io_). You will need a credit card on file for this.
3. Create an environment file (.env). Copy your IPFS project ID and API secret key to that .env file under this format:
`INFURA_IPFS_PROJECT_ID=YOUR_PROJECT_ID`
`INFURA_IPFS_PROJECT_SECRET=YOUR_SECRET`
4. Deploy smart contract first by running: `npx hardhat run scripts/deploy.js --network localhost`
5. Create local nodes: `npx hardhat node`. Import one of the accounts to metamask (Remember to switch your metamask account network to localhost instead of ethereum mainnet also).
6. Run your front-end: `npm run dev`
7. Try creating some listings then go back to home page to see if those listings are fetched.

### CODE REVIEW

**Comment by MichaelFauht** [comment]
Great work! Works well - for my own future reference I had to swap steps 5 and 4, and update the DEDICATED_URL in createlisting.js

image

I could see a user entering "30$" as the price, so with some error handling for the dollar sign it looks great to me 👍

**Review by MichaelFauht — CHANGES_REQUESTED** [review]
Great work! Works well - for my own future reference I had to swap steps 5 and 4, and update the DEDICATED_URL in createlisting.js

image

I could see a user entering "30$" as the price, so with some error handling for the dollar sign it looks great to me 👍

**Comment by axelnguyen0701** [comment]
@MichaelFauht I think its more of a front-end stuff than IPFS or blockchain thing. I think we could create a new branch to impose some validations on the form inputs so this won't happen.

**Review by MichaelFauht — APPROVED** [review]
Fair point, I can work on that in a bug fix branch along wit the overflow

**Pull request merged**
